version: '3'

services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  webapi:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/opt/talkchapwebapi
    ports:
      - "8000:8000"
    depends_on:
      - db
